version: '3.8'

services:

  app:

    env_file:
      - .env

    build:
      context: .
      dockerfile: DockerFile



    volumes:
      - .:/app

    ports:
      - ${DC_PORTS}

    depends_on:
      - db

  db:

    container_name: user_mng_db

    env_file:
      - .env

    image: postgres:15-alpine

    volumes:
      - postgres_data:/var/lib/postgresql/data/

    ports:
      - ${DB_PORT}

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"


volumes:
  postgres_data: