version: '3.8'

services:

  app:

    build:
      context: .
      dockerfile: DockerFile

    command: uvicorn src.main:app --host 0.0.0.0

    volumes:
      - .:/app

    ports:
      - "8008:8000"

    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5432/asyncalchemy
    depends_on:
      - db

  db:

    image: postgres:15-alpine

    volumes:
      - postgres_data:/var/lib/postgresql/data/

    expose:
      - 5432

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=asyncalchemy
volumes:
  postgres_data: